name: move
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  google_fonts: ^6.3.2
  flutter_switch: ^0.3.2
  provider: ^6.1.5+1
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  google_sign_in: ^6.1.0
  carousel_slider: ^5.1.1
  cached_network_image: ^3.4.1
  animated_bottom_navigation_bar: ^1.4.0
  url_launcher: ^6.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/


flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  template_arbs:
    - app_en.arb
  output_dir: lib/l10n
